name: faux_the_game
description: Cool game to play with friends and family

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.10+1
  google_fonts: ^1.1.0
  numberpicker: ^1.2.1
  carousel_slider: ^2.2.1
  font_awesome_flutter: ^8.10.0
  flag: ^3.0.5
  smooth_page_indicator: ^0.2.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/FauxLogo.png
    - l10n/en.json
    - l10n/es.json
